ada_decay_rate: 0.9999
ada_epsilon: 1e-8
avg_decay_rate: 0.999993
back_propagate_input: true
dense_grad: dense_grad_for_fetch:0
embedding:
  create_threshold: 0
  initial_g2sum: 3
  initial_range: 1e-4
  learning_rate: 0.05
  slots_config:
  - dim: 64
    dtype: float32
    expand: 128
    input_name: user_history_click_list
    slots: '1'
    update_type: gradient
  - dim: 64
    dtype: float32
    expand: 63
    input_name: position_embeddings
    slots: '2'
    update_type: gradient
  version_aware: true
  weight_bounds:
  - -10
  - 10
extra_params: []
global_init_range: 0.2
grad_scale: truediv_3:0
graph: ./conf/graph.pb
graph_extra_outputs: {}
graph_output_labels:
- Fill:0
graph_q_valid:
  auc: Fill_1:0
  loss: Fill_1:0
graph_summary: Merge/MergeSummary:0
graph_targets:
- opt
graph_tensor_mapping:
  auc: mul_7:0
  loss: mul_6:0
hyperparameter_kconf: null
hyperparameters: []
is_train_placeholder: is_train:0
learning_rate: 5.6e-07
local_init_op: ''
loss_scale_placeholder: loss_scale:0
mom_decay_rate: 0.99
output_hidden_units: ''
param:
- coln: 1
  name: num_blocks_0/ln/beta
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_0/ln/gamma
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  name: num_blocks_0/self_attention/dense/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_0/self_attention/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  name: num_blocks_0/self_attention/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_0/self_attention/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  name: num_blocks_0/self_attention/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_0/self_attention/dense_2/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_0/ln_1/beta
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_0/ln_1/gamma
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  name: num_blocks_0/multihead_attention/conv1d/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  name: num_blocks_0/multihead_attention/conv1d/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  name: num_blocks_0/multihead_attention/conv1d_1/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  name: num_blocks_0/multihead_attention/conv1d_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_1/ln/beta
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_1/ln/gamma
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  name: num_blocks_1/self_attention/dense/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_1/self_attention/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  name: num_blocks_1/self_attention/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_1/self_attention/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  name: num_blocks_1/self_attention/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_1/self_attention/dense_2/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_1/ln_1/beta
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  name: num_blocks_1/ln_1/gamma
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  name: num_blocks_1/multihead_attention/conv1d/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  name: num_blocks_1/multihead_attention/conv1d/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  name: num_blocks_1/multihead_attention/conv1d_1/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  name: num_blocks_1/multihead_attention/conv1d_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
q_label:
- auc_set: linear_regression
  label: Fill:0
  name: loss
- auc_set: linear_regression
  label: Fill:0
  name: auc
q_names: loss auc
sparse_grad: sparse_grad_for_fetch:0
sparse_grad_scale: truediv_4:0
summary:
- len: 640
  name: one_u_summary
- len: 384
  name: one_p_summary
- len: 504
  name: two_u_summary
- len: 256
  name: two_p_summary
summary_decay_rate: 0.999999
summary_init_n: 1e4
summary_init_squared_sum: 1e4
summary_squared_sum_epsilon: 1e-4
test_layers_at_joining: join join_forward update update_forward
test_layers_at_updating: update update_forward
test_mode: false
train_layers_at_joining: join
train_layers_at_updating: update
use_sparse_indice: false
vec_input:
- common: false
  dim: 1
  name: mask
- common: false
  dim: 1
  name: click
with_kai: true
