# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bt_shm_kv.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62t_shm_kv.proto\x12\x0e\x62\x61se.bt_shm_kv\"2\n\rGetKeyRequest\x12\x10\n\x08part_num\x18\x01 \x01(\x05\x12\x0f\n\x07part_id\x18\x02 \x01(\x05\"/\n\x0eGetKeyResponse\x12\x0b\n\x03key\x18\x01 \x03(\x04\x12\x10\n\x08too_many\x18\x02 \x01(\x08\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x03(\x04\"g\n\x0cReadResponse\x12\x0b\n\x03key\x18\x01 \x03(\x04\x12\r\n\x05value\x18\x02 \x03(\x0c\x12\x14\n\x0c\x65xpire_timet\x18\x03 \x03(\r\x12\x10\n\x08too_many\x18\x04 \x01(\x08\x12\x13\n\x0bio_too_much\x18\x05 \x01(\x08\"\x10\n\x0eGetMetaRequest\"9\n\x0fGetMetaResponse\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x15\n\rexternal_data\x18\x02 \x01(\x0c\"!\n\x10GetMetaV2Request\x12\r\n\x05token\x18\x01 \x01(\x0c\">\n\x11GetMetaV2Response\x12\r\n\x05token\x18\x01 \x01(\x0c\x12\x0c\n\x04more\x18\x02 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32\xe8\x01\n\x0e\x42TShmKVService\x12G\n\x06GetKey\x12\x1d.base.bt_shm_kv.GetKeyRequest\x1a\x1e.base.bt_shm_kv.GetKeyResponse\x12\x41\n\x04Read\x12\x1b.base.bt_shm_kv.ReadRequest\x1a\x1c.base.bt_shm_kv.ReadResponse\x12J\n\x07GetMeta\x12\x1e.base.bt_shm_kv.GetMetaRequest\x1a\x1f.base.bt_shm_kv.GetMetaResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bt_shm_kv_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETKEYREQUEST']._serialized_start=35
  _globals['_GETKEYREQUEST']._serialized_end=85
  _globals['_GETKEYRESPONSE']._serialized_start=87
  _globals['_GETKEYRESPONSE']._serialized_end=134
  _globals['_READREQUEST']._serialized_start=136
  _globals['_READREQUEST']._serialized_end=162
  _globals['_READRESPONSE']._serialized_start=164
  _globals['_READRESPONSE']._serialized_end=267
  _globals['_GETMETAREQUEST']._serialized_start=269
  _globals['_GETMETAREQUEST']._serialized_end=285
  _globals['_GETMETARESPONSE']._serialized_start=287
  _globals['_GETMETARESPONSE']._serialized_end=344
  _globals['_GETMETAV2REQUEST']._serialized_start=346
  _globals['_GETMETAV2REQUEST']._serialized_end=379
  _globals['_GETMETAV2RESPONSE']._serialized_start=381
  _globals['_GETMETAV2RESPONSE']._serialized_end=443
  _globals['_BTSHMKVSERVICE']._serialized_start=446
  _globals['_BTSHMKVSERVICE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
