# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='embedding_server.proto',
  package='ks.reco',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x16\x65mbedding_server.proto\x12\x07ks.reco\")\n\x18GetKuibaEmbeddingRequest\x12\r\n\x05signs\x18\x01 \x03(\x04\":\n\x19GetKuibaEmbeddingResponse\x12\r\n\x05signs\x18\x01 \x03(\x04\x12\x0e\n\x06values\x18\x02 \x03(\x0c\x32p\n\x12PredictKessService\x12Z\n\x11GetKuibaEmbedding\x12!.ks.reco.GetKuibaEmbeddingRequest\x1a\".ks.reco.GetKuibaEmbeddingResponse'
)




_GETKUIBAEMBEDDINGREQUEST = _descriptor.Descriptor(
  name='GetKuibaEmbeddingRequest',
  full_name='ks.reco.GetKuibaEmbeddingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signs', full_name='ks.reco.GetKuibaEmbeddingRequest.signs', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=76,
)


_GETKUIBAEMBEDDINGRESPONSE = _descriptor.Descriptor(
  name='GetKuibaEmbeddingResponse',
  full_name='ks.reco.GetKuibaEmbeddingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signs', full_name='ks.reco.GetKuibaEmbeddingResponse.signs', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='ks.reco.GetKuibaEmbeddingResponse.values', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['GetKuibaEmbeddingRequest'] = _GETKUIBAEMBEDDINGREQUEST
DESCRIPTOR.message_types_by_name['GetKuibaEmbeddingResponse'] = _GETKUIBAEMBEDDINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetKuibaEmbeddingRequest = _reflection.GeneratedProtocolMessageType('GetKuibaEmbeddingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETKUIBAEMBEDDINGREQUEST,
  '__module__' : 'embedding_server_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.GetKuibaEmbeddingRequest)
  })
_sym_db.RegisterMessage(GetKuibaEmbeddingRequest)

GetKuibaEmbeddingResponse = _reflection.GeneratedProtocolMessageType('GetKuibaEmbeddingResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETKUIBAEMBEDDINGRESPONSE,
  '__module__' : 'embedding_server_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.GetKuibaEmbeddingResponse)
  })
_sym_db.RegisterMessage(GetKuibaEmbeddingResponse)



_PREDICTKESSSERVICE = _descriptor.ServiceDescriptor(
  name='PredictKessService',
  full_name='ks.reco.PredictKessService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=138,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetKuibaEmbedding',
    full_name='ks.reco.PredictKessService.GetKuibaEmbedding',
    index=0,
    containing_service=None,
    input_type=_GETKUIBAEMBEDDINGREQUEST,
    output_type=_GETKUIBAEMBEDDINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICTKESSSERVICE)

DESCRIPTOR.services_by_name['PredictKessService'] = _PREDICTKESSSERVICE

# @@protoc_insertion_point(module_scope)
