# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import embedding_server_pb2 as embedding__server__pb2


class PredictKessServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKuibaEmbedding = channel.unary_unary(
                '/ks.reco.PredictKessService/GetKuibaEmbedding',
                request_serializer=embedding__server__pb2.GetKuibaEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__server__pb2.GetKuibaEmbeddingResponse.FromString,
                )


class PredictKessServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetKuibaEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictKessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKuibaEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKuibaEmbedding,
                    request_deserializer=embedding__server__pb2.GetKuibaEmbeddingRequest.FromString,
                    response_serializer=embedding__server__pb2.GetKuibaEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ks.reco.PredictKessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictKessService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetKuibaEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ks.reco.PredictKessService/GetKuibaEmbedding',
            embedding__server__pb2.GetKuibaEmbeddingRequest.SerializeToString,
            embedding__server__pb2.GetKuibaEmbeddingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
