# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bt_shm_kv_pb2 as bt__shm__kv__pb2


class KessBTShmKVServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKey = channel.unary_unary(
                '/base.bt_shm_kv.KessBTShmKVService/GetKey',
                request_serializer=bt__shm__kv__pb2.GetKeyRequest.SerializeToString,
                response_deserializer=bt__shm__kv__pb2.GetKeyResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/base.bt_shm_kv.KessBTShmKVService/Read',
                request_serializer=bt__shm__kv__pb2.ReadRequest.SerializeToString,
                response_deserializer=bt__shm__kv__pb2.ReadResponse.FromString,
                )
        self.GetMeta = channel.unary_unary(
                '/base.bt_shm_kv.KessBTShmKVService/GetMeta',
                request_serializer=bt__shm__kv__pb2.GetMetaRequest.SerializeToString,
                response_deserializer=bt__shm__kv__pb2.GetMetaResponse.FromString,
                )
        self.GetMetaV2 = channel.unary_unary(
                '/base.bt_shm_kv.KessBTShmKVService/GetMetaV2',
                request_serializer=bt__shm__kv__pb2.GetMetaV2Request.SerializeToString,
                response_deserializer=bt__shm__kv__pb2.GetMetaV2Response.FromString,
                )


class KessBTShmKVServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetaV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KessBTShmKVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKey,
                    request_deserializer=bt__shm__kv__pb2.GetKeyRequest.FromString,
                    response_serializer=bt__shm__kv__pb2.GetKeyResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=bt__shm__kv__pb2.ReadRequest.FromString,
                    response_serializer=bt__shm__kv__pb2.ReadResponse.SerializeToString,
            ),
            'GetMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeta,
                    request_deserializer=bt__shm__kv__pb2.GetMetaRequest.FromString,
                    response_serializer=bt__shm__kv__pb2.GetMetaResponse.SerializeToString,
            ),
            'GetMetaV2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetaV2,
                    request_deserializer=bt__shm__kv__pb2.GetMetaV2Request.FromString,
                    response_serializer=bt__shm__kv__pb2.GetMetaV2Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'base.bt_shm_kv.KessBTShmKVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KessBTShmKVService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base.bt_shm_kv.KessBTShmKVService/GetKey',
            bt__shm__kv__pb2.GetKeyRequest.SerializeToString,
            bt__shm__kv__pb2.GetKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base.bt_shm_kv.KessBTShmKVService/Read',
            bt__shm__kv__pb2.ReadRequest.SerializeToString,
            bt__shm__kv__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base.bt_shm_kv.KessBTShmKVService/GetMeta',
            bt__shm__kv__pb2.GetMetaRequest.SerializeToString,
            bt__shm__kv__pb2.GetMetaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetaV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base.bt_shm_kv.KessBTShmKVService/GetMetaV2',
            bt__shm__kv__pb2.GetMetaV2Request.SerializeToString,
            bt__shm__kv__pb2.GetMetaV2Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
