# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kess_bt_shm_kv.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bt_shm_kv_pb2 as bt__shm__kv__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14kess_bt_shm_kv.proto\x12\x0e\x62\x61se.bt_shm_kv\x1a\x0f\x62t_shm_kv.proto2\xbe\x02\n\x12KessBTShmKVService\x12G\n\x06GetKey\x12\x1d.base.bt_shm_kv.GetKeyRequest\x1a\x1e.base.bt_shm_kv.GetKeyResponse\x12\x41\n\x04Read\x12\x1b.base.bt_shm_kv.ReadRequest\x1a\x1c.base.bt_shm_kv.ReadResponse\x12J\n\x07GetMeta\x12\x1e.base.bt_shm_kv.GetMetaRequest\x1a\x1f.base.bt_shm_kv.GetMetaResponse\x12P\n\tGetMetaV2\x12 .base.bt_shm_kv.GetMetaV2Request\x1a!.base.bt_shm_kv.GetMetaV2Response')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kess_bt_shm_kv_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KESSBTSHMKVSERVICE']._serialized_start=58
  _globals['_KESSBTSHMKVSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
