# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x08ks.model\"\xc0\x01\n\tModelItem\x12\r\n\x05\x63ount\x18\x01 \x01(\x0c\x12\x18\n\x10\x65mbedding_weight\x18\x02 \x01(\x0c\x12\x11\n\tlr_weight\x18\x03 \x01(\x0c\x12\x14\n\x0c\x65xpire_timet\x18\x04 \x01(\r\x12\x0c\n\x04sign\x18\x05 \x01(\x04\x12\x0c\n\x04slot\x18\x06 \x01(\x05\x12\x0b\n\x03val\x18\x07 \x01(\x05\x12\x0e\n\x06\x65xt_id\x18\x08 \x01(\x04\x12\x15\n\rfeature_score\x18\t \x01(\x02\x12\x11\n\tupdate_ts\x18\n \x01(\r\">\n\tModelPart\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x13\n\x0bpart_binary\x18\x03 \x01(\x0c\"\xd7\x01\n\x12ModelUpdateMessage\x12!\n\x04item\x18\x01 \x03(\x0b\x32\x13.ks.model.ModelItem\x12\x11\n\thas_count\x18\x02 \x01(\x08\x12\x1d\n\x15\x65mbedding_weight_size\x18\x03 \x01(\x05\x12\x16\n\x0elr_weight_size\x18\x04 \x01(\x05\x12\x0f\n\x07version\x18\x05 \x01(\x03\x12\'\n\nmodel_part\x18\x06 \x01(\x0b\x32\x13.ks.model.ModelPart\x12\x1a\n\x12\x65nable_fp32_weight\x18\x07 \x01(\x08\"\x91\x01\n\nCausalLog2\x12\r\n\x05llsid\x18\x01 \x02(\x03\x12\x14\n\x0cnr_user_type\x18\x02 \x02(\x03\x12\x10\n\x08province\x18\x03 \x02(\t\x12\x11\n\tdevice_id\x18\x04 \x02(\t\x12\x15\n\rcausal_params\x18\x05 \x03(\x02\x12\r\n\x05stamp\x18\x06 \x02(\x03\x12\x13\n\x0bmeta_params\x18\x07 \x03(\x03\x42\x03\xf8\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _globals['_MODELITEM']._serialized_start=26
  _globals['_MODELITEM']._serialized_end=218
  _globals['_MODELPART']._serialized_start=220
  _globals['_MODELPART']._serialized_end=282
  _globals['_MODELUPDATEMESSAGE']._serialized_start=285
  _globals['_MODELUPDATEMESSAGE']._serialized_end=500
  _globals['_CAUSALLOG2']._serialized_start=503
  _globals['_CAUSALLOG2']._serialized_end=648
# @@protoc_insertion_point(module_scope)
