ada_decay_rate: 0.9999
ada_epsilon: 1e-8
avg_decay_rate: 0.999993
back_propagate_input: true
dense_grad: dense_grad_for_fetch:0
embedding:
  slots_config: []
extra_params: []
global_init_range: 0.2
grad_scale: truediv_3:0
graph: .././graph.pb
graph_extra_outputs: {}
graph_output_labels:
- Fill:0
graph_q_valid:
  auc: Fill_1:0
  loss: Fill_1:0
graph_summary: Merge/MergeSummary:0
graph_targets:
- opt
graph_tensor_mapping:
  embs: MatMul_3:0
  z: Reshape:0
hyperparameter_kconf: null
hyperparameters: []
input_type: 3
is_train_placeholder: is_train:0
learning_rate: 5.6e-07
local_init_op: ''
loss_scale_placeholder: loss_scale:0
mom_decay_rate: 0.99
output_hidden_units: ''
param: []
q_names: embs z
sparse_grad: sparse_grad_for_fetch:0
sparse_grad_scale: truediv_4:0
summary:
- len: 640
  name: one_u_summary
- len: 384
  name: one_p_summary
- len: 504
  name: two_u_summary
- len: 256
  name: two_p_summary
summary_decay_rate: 0.999999
summary_init_n: 1e4
summary_init_squared_sum: 1e4
summary_squared_sum_epsilon: 1e-4
test_layers_at_joining: join join_forward update update_forward
test_layers_at_updating: update update_forward
test_mode: false
train_layers_at_joining: join
train_layers_at_updating: update
use_sparse_indice: false
vec_input:
- common: false
  dim: 16
  name: tokens
with_kai: true
