output_names:
- embs
param:
- coln: 32
  name: model.quantizer.embed.weight
  need_transpose: false
  rown: 512
  th_tensor_name: model.quantizer.embed.weight
- coln: 512
  name: onnx::MatMul_33
  need_transpose: true
  rown: 512
  th_tensor_name: model.decoder.w1.weight
- coln: 512
  name: onnx::MatMul_34
  need_transpose: true
  rown: 512
  th_tensor_name: model.decoder.w3.weight
- coln: 512
  name: onnx::MatMul_35
  need_transpose: true
  rown: 128
  th_tensor_name: model.decoder.w2.weight
